### PR TITLE
Fix #2429 - Update button compat with NETCORE

### LINKED ISSUE #2429: [Bug]: update button in 2025
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

when running the update button in revit 2025.3, it throws the following error:
`INFO [pyrevit.versionmgr.updater] Checking internet connection... `

### ⌨ Error/Debug Message

```shell
INFO [pyrevit.versionmgr.updater] Checking internet connection...
```

### ♻️ To Reproduce

_No response_

### ⏲️ Expected behavior

to update extensions

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
-
```

### Additional context

The checking of the internet connection is not working in 2025, I need to check later

### PR DESCRIPTION
**Pull request by jmcouffin**
fix #2429

### CODE REVIEW

**Comment by dosymep** [comment]
@jmcouffin maybe try to use [Ping](https://learn.microsoft.com/ru-ru/dotnet/api/system.net.networkinformation.ping?view=netframework-4.8)?

**Comment by jmcouffin** [comment]
> @jmcouffin maybe try to use [Ping](https://learn.microsoft.com/en-us/dotnet/api/system.net.networkinformation.ping?view=netframework-4.8)?

I will have a look eventually, 
I am a bit swamped with work right now.

**Comment by sanzoghenzo** [comment]
Do we really need to check the connection before doing anything?

- `can_access_url` is only used by `check_internet_connection`;
- `check_internet_connection` uses (not-so-)random urls that have nothing to do with the update process (well, only github.com does), and returns the first successful url, but nobody cares about it
- `check_internet_connection` is only used by `versionmgr.updater._check_connection` that actually "cares" about that url, just to display a debug message and return True

[This SO answer](https://stackoverflow.com/a/33117579/4149512) suggests using socket and a fixed ip address and tcp port instead of relying on name resolutions and application layers.
Here's the code, that I would put in the _check_connection function and discard the other two functions
Not sure if it plays well with IronPython/python.net, though...

```python
import socket

def _check_connection(host="8.8.8.8", port=53, timeout=3):
    """
    Host: 8.8.8.8 (google-public-dns-a.google.com)
    OpenPort: 53/tcp
    Service: domain (DNS/TCP)
    """
    try:
        socket.setdefaulttimeout(timeout)
        socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect((host, port))
        return True
    except socket.error as ex:
        print(ex)
        return False
```

**Comment by sanzoghenzo** [comment]
I didn't test it, but something like this should work

```python
from System.Net.NetworkInformation import Ping, IPStatus

def _check_connection(ip_address="8.8.8.8"):
    ping_sender = Ping()
    try:
        reply = ping_sender.Send(ip_address)
    except Exception:
        return False
    return reply.Status == IPStatus.Success
```

**Comment by jmcouffin** [comment]
> I didn't test it, but something like this should work
> 
> ```python
> from System.Net.NetworkInformation import Ping, IPStatus
> 
> def _check_connection(ip_address="8.8.8.8"):
>     ping_sender = Ping()
>     try:
>         reply = ping_sender.Send(ip_address)
>     except Exception:
>         return False
>     return reply.Status == IPStatus.Success
> ```

this did not work.

**Comment by jmcouffin** [comment]
> ~Do we really need to check the connection before doing anything?~ It makes sense if we don't want to crash the code with timeout exceptions... anyway:
> 
> * `can_access_url` is only used by `check_internet_connection`;
> * `check_internet_connection` uses (not-so-)random urls that have nothing to do with the update process (well, only github.com does), and returns the first successful url, but nobody cares about it
> * `check_internet_connection` is only used by `versionmgr.updater._check_connection` that actually "cares" about that url, just to display a debug message and return True
> 
> [This SO answer](https://stackoverflow.com/a/33117579/4149512) suggests using socket and a fixed ip address and tcp port instead of relying on name resolutions and application layers. Here's the code, that I would put in the _check_connection function and discard the other two functions Not sure if it plays well with IronPython/python.net, though...
> 
> ```python
> import socket
> 
> def _check_connection(host="8.8.8.8", port=53, timeout=3):
>     """
>     Host: 8.8.8.8 (google-public-dns-a.google.com)
>     OpenPort: 53/tcp
>     Service: domain (DNS/TCP)
>     """
>     try:
>         socket.setdefaulttimeout(timeout)
>         socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect((host, port))
>         return True
>     except socket.error as ex:
>         print(ex)  # change it with some logging
>         return False
> ```
> 
> Obviously the .net Ping solution could be the best solution, so that we can port the core of pyrevit to .NET more easily 😉

on the contrary, this did work (tested in 2022 and 2025)

**Comment by tay0thman** [comment]
Testing WIP build: [5.0.0.24309+2043-wip]

IronPython Traceback:
Traceback (most recent call last):
  File "C:\Program Files\pyRevit-Master\bin\netcore\engines\pyRevitLoader.py", line 30, in <module>
  File "C:\Program Files\pyRevit-Master\pyrevitlib\pyrevit\loader\sessionmgr.py", line 30, in <module>
  File "C:\Program Files\pyRevit-Master\pyrevitlib\pyrevit\versionmgr\updater.py", line 14, in <module>
**ImportError: No module named NetworkInformation**

**Pull request merged**
