### PR TITLE
netcore support

### PR DESCRIPTION
**Pull request by sanzoghenzo**
Let's do this 😉

### CODE REVIEW

**Comment by sanzoghenzo** [comment]
There's still something missing, checking now...

**Comment by sanzoghenzo** [comment]
Ok, I overlook a folder, everything seems fine!

@jmcouffin  Do you want to do another test with my fork installer before merging?

https://github.com/sanzoghenzo/pyRevit/actions/runs/10383201975

**Comment by jmcouffin** [comment]
> @jmcouffin Do you want to do another test with my fork installer before merging?

Doing it

**Comment by jmcouffin** [comment]
> Ok, I overlook a folder, everything seems fine!
> 
> @jmcouffin Do you want to do another test with my fork installer before merging?
> 
> https://github.com/sanzoghenzo/pyRevit/actions/runs/10383201975

It seems to work just fine.
I picked up a small bug on the way but nothing serious...
Merging

**Comment by jmcouffin** [comment]
I will let you handle the workflow remix @sanzoghenzo 
You have played with it more than me lately

**Comment by jmcouffin** [comment]
another thing needs to be done (again) merging the develop-4 to develop if you don't mind taking care of it? I don't want to redo the mess I did yesterday ;p

**Comment by sanzoghenzo** [comment]
> another thing needs to be done (again) merging the develop-4 to develop if you don't mind taking care of it? I don't want to redo the mess I did yesterday ;p

Is this necessary? develop-4 is there for pyrevit4, but this PR is regarding pyrevit 5.
Also, since we've planning on dropping develop-4, it is pretty useless to do this.
Or am I missing something?

**Comment by jmcouffin** [comment]
> EDIT: it's already been done with the merge and squash commit you did yesterday😉

the branch comparison in GH was misleading, I tried to compare the develop to develop-4 and it seemed to compare old stuff.
doing a cherry picked comparison showed that you are right.

So workflows remain only.

**Comment by jmcouffin** [comment]
if you don't mind, I'd rather have a real conversation through Slack(pythonAEC) or Zoom or Teams

**Pull request merged**
