### PR TITLE
netcore: Merging dosymep/netcore to develop 4

### PR DESCRIPTION
**Pull request by jmcouffin**

### CODE REVIEW

**Comment by jmcouffin** [comment]
@sanzoghenzo @dosymep I am having difficulties making this not a mess 😩 
Any advice appreciated

**Comment by sanzoghenzo** [comment]
Sorry I was at work until now, and I'm heading out...
You can just copy the missing .cs files from the commit before the merge and create a new commit with only those files (be it as a new pr or directly on develop)

**Comment by sanzoghenzo** [comment]
Sorry, I see only now that it is a different PR and that you tried various things unsuccessfully 😉 

I would do the following:

- do an hard reset and force push of the develop and develop-4 branches to set it to what they were before #2088 was merged
- add the missing files to dosymep/netcore
- do a new PR with the updated dosymep/netcore

I started working on the last two points, I hope to get something working by tomorrow at noon or before.

**Comment by sanzoghenzo** [comment]
Closing this in, @jmcouffin you've got a DM on discourse for how to solve this 😉

**Comment by jmcouffin** [comment]
> Closing this in, @jmcouffin you've got a DM on discourse for how to solve this 😉

Looking at it in a few minutes.

**Pull request closed without merging**
