### PR TITLE
add autosave extension to extensions list

### PR DESCRIPTION
**Pull request by alexdaversa**
Would appreciate others giving this a test--something about my local git setup is interfering with my ability to install extensions (unknown certificate lookup failure: 16777280)

### CODE REVIEW

**Comment by jmcouffin** [comment]
It works for me:
image
except for this bit 
```python
IronPython Traceback:
Traceback (most recent call last):
 File "C:\pyRevit\pyRevit-Autosave.extension\pyRevit.tab\Autosave.panel\Autosave.stack\Autosave.smartbutton\script.py", line 58, in <module>
 File "C:\Users\Jean-MarcCouffin\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\script.py", line 499, in toggle_icon
AttributeError: '_PyRevitRibbonPanel' object has no attribute 'set_icon'

Script Executor Traceback:
System.MissingMemberException: '_PyRevitRibbonPanel' object has no attribute 'set_icon'
 à IronPython.Runtime.Binding.MetaUserObject.FastGetBinderHelper.<>c__DisplayClass16_0.<FallbackError>b__1(CallSite site, Object self, CodeContext context)
 à IronPython.Runtime.Types.GetMemberDelegates.SlotDict(CallSite site, Object self, CodeContext context)
 à System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
 à IronPython.Compiler.Ast.DynamicGetMemberExpression.GetMemberInstruction.Run(InterpretedFrame frame)
 à Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 à Microsoft.Scripting.Interpreter.LightLambda.Run5[T0,T1,T2,T3,T4,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
 à IronPython.Compiler.PythonCallTargets.OriginalCallTarget4(PythonFunction function, Object arg0, Object arg1, Object arg2, Object arg3)
 à IronPython.Runtime.FunctionCaller`1.Default3Call1(CallSite site, CodeContext context, Object func, T0 arg0)
 à System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
 à Microsoft.Scripting.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
 à Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 à Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 à IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 à PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)
```

**Comment by alexdaversa** [comment]
Interesting! This took me a bit to figure out what was happening--it seems like the get_all_buttons function in pyrevit.script is finding all children that match the name "Autosave" which includes the panel and stack, and then toggle_icon tries to toggle their icon, which it cannot do. I may propose a PR for get_all_buttons in the future to be more specific about what it matches (no panels or stacks as they do not have icons).

In the meantime I have changed the name of the smartbutton in my extension to be unique, so it should work again.

Thank you for testing!!!

**Comment by jmcouffin** [comment]
> Thank you for testing!!!

no pb


do you want me to add your extension and merge the PR then?

**Comment by alexdaversa** [comment]
Yes please 😄

**Pull request merged**
