### PR TITLE
docs: add developer guides

### PR DESCRIPTION
**Pull request by sanzoghenzo**
I finally found the time to create what I promised:

- turned the developer guide that we discussed on the forum to a docs page
- added an architecture guide to understand the loading process and script execution
- added a page with a really brief description of the various folders found in the repository

I updated MkDocs and dependencies in the process, so if you want to check it out locally you need to

```shell
pipenv sync
pipenv run mkdocs serve
```

### CODE REVIEW

**Review by jmcouffin — APPROVED** [review]

**Comment by jmcouffin** [comment]
This great @sanzoghenzo 
And very much needed for the future of the beast

**Comment by jmcouffin** [comment]
As if it were that simple 🤣😁😐
https://github.com/pyrevitlabs/pyRevit/actions/runs/12508207664/job/34895953611#step:10:1

**Comment by sanzoghenzo** [comment]
maybe we can solve that by changing [this line](https://github.com/pyrevitlabs/pyRevit/blob/cab55a3c7365a1c8aa96529b46b29340a350729f/.github/workflows/docs.yml#L38) to `pipenv sync` (this will make sure that the packages used are the same as in the pipfile.lock, so exactly the same as the ones I used on my machine).

I'll try tomorrow, I'm too tired now to break things now :sweat_smile:

**Comment by jmcouffin** [comment]
Trying it right now.
Let's break things a bit more.

**Comment by jmcouffin** [comment]
Neither broken nor fixed

**Comment by sanzoghenzo** [comment]
Oh, I now see that colorama is flagged to be installed only on windows

https://github.com/pyrevitlabs/pyRevit/blob/9fbe2d3bbf10c590cc470980c3925b21e1e963f9/Pipfile.lock#L183

I'll try to fix it as soon as I get back to my pc

**Pull request merged**
