### PR TITLE
Set Revision On Sheets.pushbutton - Filter out issued revisions

### PR DESCRIPTION
**Pull request by tay0thman**
Excluding the revisions that are marked as issued as it won't be possible to apply them to sheets. Added filter function

### CODE REVIEW

**Comment by jmcouffin** [comment]
Hi @tay0thman 
Thanks for this improvement.
Please use the develop-4 branch for your next improvements as this is the branch we use for wip modifications before issuing a release and pushing to the base branch.

**Comment by tay0thman** [comment]
Thank you @jmcouffin  It's my first contribution on Github ever, so If I find anything helpful in the future I'll make sure to pick the right branch.

**Comment by tay0thman** [comment]
Thank you @jmcouffin  It's my first contibution, so If I find anything helpful in the future I'll make sure to

**Comment by jmcouffin** [comment]
> Thank you @jmcouffin It's my first contribution on Github ever, so If I find anything helpful in the future I'll make sure to pick the right branch.

No PB at all, this is a great first.
Keep on!

**Pull request merged**
